# .github/workflows/ci-docker.yml
name: CI · Build & Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/proyecto2-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpwd
          MYSQL_DATABASE: farmaceutica
          MYSQL_USER: usuario
          MYSQL_PASSWORD: usuariopwd
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        # <-- elimina ports: - 3306:3306

    steps:
      
uses: actions/checkout@v4,

      
uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '21'
        cache: maven,

      
name: Wait for MySQL to be ready
      run: |
        for i in {1..30}; do
          if mysqladmin ping -h mysql --silent; then
            echo "MySQL is up!"
            break
          fi
          echo "Waiting for MySQL..."
          sleep 2
        done,

      
name: Build & run tests
      env:
        SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/farmaceutica
        SPRING_DATASOURCE_USERNAME: usuario
        SPRING_DATASOURCE_PASSWORD: usuariopwd
      run: mvn clean verify --batch-mode
