# .github/workflows/ci-docker.yml
name: CI · Build, Push Docker Image & Update CD Repo

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  #IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/proyecto2-app
  IMAGE_NAME: gcr.io/deep-theorem-461601-j3/mi-aplicacion

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpwd
          MYSQL_DATABASE: farmaceutica
          MYSQL_USER: usuario
          MYSQL_PASSWORD: usuariopwd
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
        # <-- elimina ports: - 3306:3306

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 & cache Maven deps
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven


      - name: Wait for MySQL to be ready
        run: |
          for i in {1..30}; do  
            if mysqladmin ping -h mysql --silent; then
              echo "MySQL is up!"
              break
            fi
            echo "Waiting for MySQL..."
            sleep 2
          done

      - name: Build & run tests
        env:
          SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/farmaceutica
          SPRING_DATASOURCE_USERNAME: usuario
          SPRING_DATASOURCE_PASSWORD: usuariopwd
        run: mvn clean verify --batch-mode

      - name: Configure Docker for GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: Set up Docker with gcloud
        run: gcloud auth configure-docker --quiet

      - name: Build and push Docker image
        run: |
          TAG=$(echo $GITHUB_SHA | cut -c1-7)
          docker build -t $IMAGE_NAME:$TAG .
          docker push $IMAGE_NAME:$TAG
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Update CD repo with new image tag
        env:
          GIT_AUTHOR_NAME: github-actions
          GIT_AUTHOR_EMAIL: actions@github.com
        run: |
          git config --global user.name "$GIT_AUTHOR_NAME"
          git config --global user.email "$GIT_AUTHOR_EMAIL"

          git clone https://x-access-token:${{ secrets.CD_REPO_TOKEN }}@github.com/Joaco202/Proyecto2-CI.git cd-repo
          cd cd-repo

          sed -i "s|image: gcr.io/deep-theorem-461601-j3/mi-aplicacion:.*|image: gcr.io/deep-theorem-461601-j3/mi-aplicacion:$TAG|g" mi-aplicacion/deployment.yaml

          git add mi-aplicacion/deployment.yaml
          git commit -m "Actualiza tag de imagen a $TAG desde CI"
          git push origin main
