# .github/workflows/ci-docker.yml
name: CI · Build & Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_USERNAME }}/proyecto2-app

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21 & cache Maven deps
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'            # ← aquí cambias de 17 a 21
          cache: maven

      - name: Build & run tests
        run: mvn clean verify --batch-mode

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
         debug: true
          username: ${{ secrets.joacocon }}
          password: ${{ secrets.Pokemin_1 }}

      - name: Build & push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.sha }}
